const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let certPage=1;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=1)=>Number(v??0).toLocaleString('pt-BR',{maximumFractionDigits:d});
const dateBR=v=>{if(!v)return'—';const p=String(v).slice(0,10).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v};
const station=v=>{const n=Number(v);return Number.isFinite(n)?`${Math.floor(n/1000)}+${String(Math.round(n%1000)).padStart(3,'0')}`:'—'};
const badge=v=>{const s=String(v||'SEM RESULTADO');const cls=s==='APROVADO'?'ok':s==='REPROVADO'?'bad':'warn';return `<span class="badge ${cls}">${esc(s)}</span>`};
const query=o=>{const p=new URLSearchParams();Object.entries(o).forEach(([k,v])=>{if(v!==''&&v!=null)p.set(k,v)});return p};
async function api(url){const r=await fetch(url);const d=await r.json();if(!r.ok)throw new Error(d.detail||'Falha na API');return d}
function filters(){return{contractor:$('#contractor').value,measurement:$('#measurement').value}}
function toast(m){const e=$('#toast');e.textContent=m;e.style.display='block';setTimeout(()=>e.style.display='none',3500)}
async function loadDashboard(){const d=await api('/api/dashboard?'+query(filters()));$('#kpis').innerHTML=[
  ['Certificados',d.certificates,'Registros no filtro'],['Aprovados',d.approved,'Resultado técnico'],['Reprovados',d.reproved,'Resultado técnico'],['Pendências',d.pending_days,'Dias sem certificado válido'],
  ['Medições',d.measurements,'Linhas operacionais'],['Quantidade',num(d.quantity_t,1)+' t','Volume sintético'],['Sem resultado',d.without_result,'Aguardando ensaio'],['Status','Online','FastAPI']
].map(x=>`<div class="kpi"><small>${esc(x[0])}</small><b>${esc(x[1])}</b><span>${esc(x[2])}</span></div>`).join('');
$('#recent').innerHTML='<div class="table-wrap"><table><thead><tr><th>Certificado</th><th>Contratada</th><th>Data</th><th>Rodovia</th><th>Vv</th><th>A/B</th><th>Status</th></tr></thead><tbody>'+d.recent.map(x=>`<tr><td><b>${esc(x.number)}</b></td><td>${esc(x.contractor)}</td><td>${dateBR(x.service_date)}</td><td>${esc(x.road)}</td><td>${x.vv==null?'—':num(x.vv,1)+'%'}</td><td>${x.ab==null?'—':num(x.ab,1)+'%'}</td><td>${badge(x.status)}</td></tr>`).join('')+'</tbody></table></div>'}
async function loadCertificates(page=1){certPage=page;const f=filters(),search=$('#certificate-search').value;const d=await api('/api/certificates?'+query({...f,search,page,page_size:30}));$('#certificate-body').innerHTML=d.items.map(x=>`<tr><td><b>${esc(x.number)}</b></td><td>${esc(x.contractor)}</td><td>${dateBR(x.service_date)}</td><td>${esc(x.road)}</td><td>${station(x.kmi)}–${station(x.kmf)}</td><td>${esc(x.trace)}</td><td>${x.vv==null?'—':num(x.vv,1)+'%'}</td><td>${x.ab==null?'—':num(x.ab,1)+'%'}</td><td>${badge(x.status)}</td></tr>`).join('');const from=d.total?(d.page-1)*d.page_size+1:0,to=Math.min(d.total,d.page*d.page_size);$('#certificate-pagination').innerHTML=`<span>${from}–${to} de ${d.total}</span><span><button id="prev" ${page<=1?'disabled':''}>Anterior</button> <button id="next" ${to>=d.total?'disabled':''}>Próxima</button></span>`;$('#prev').onclick=()=>loadCertificates(page-1);$('#next').onclick=()=>loadCertificates(page+1)}
async function loadPending(){const d=await api('/api/pending?'+query(filters()));$('#pending-body').innerHTML=d.items.map(x=>`<tr><td>${esc(x.contractor)}</td><td>${dateBR(x.date)}</td><td>${esc(x.road)}</td><td>${station(x.kmi)}–${station(x.kmf)}</td><td>${esc(x.lane)}</td><td>${num(x.quantity_t,1)} t</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma pendência no filtro.</td></tr>'}
async function loadMeasurements(){const d=await api('/api/measurements?'+query({...filters(),page:1,page_size:40}));$('#measurement-body').innerHTML=d.items.map(x=>`<tr><td>${esc(x.contractor)}</td><td>${dateBR(x.date)}</td><td>${esc(x.road)}</td><td>${station(x.kmi)}–${station(x.kmf)}</td><td>${esc(x.lane)}</td><td>${num(x.quantity_t,1)} t</td></tr>`).join('')}
async function loadCurrent(){const p=$('.page.active').id;try{if(p==='page-dashboard')await loadDashboard();else if(p==='page-certificates')await loadCertificates(certPage);else if(p==='page-pending')await loadPending();else await loadMeasurements()}catch(e){toast(e.message)}}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+b.dataset.page).classList.add('active');$('#title').textContent=b.textContent;loadCurrent()});
$('#refresh').onclick=loadCurrent;$('#contractor').onchange=loadCurrent;$('#measurement').onchange=loadCurrent;$('#certificate-apply').onclick=()=>loadCertificates(1);$('#certificate-search').onkeydown=e=>{if(e.key==='Enter')loadCertificates(1)};loadDashboard();